[build-system]
requires = ["flit_core>=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sphinx_jinja2"
dynamic = ["version", "description"]
authors = [{name = "Chris Sewell", email = "chrisj_sewell@hotmail.com"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Sphinx :: Extension",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
]
keywords = ["sphinx", "extension", "jinja", "minijinja"]
requires-python = ">=3.11"
dependencies = ["sphinx>=7.2", "minijinja>=2.15"]

[project.urls]
Homepage = "https://github.com/sphinx-extensions2/sphinx-jinja2"
Documentation = "https://sphinx-jinja2.readthedocs.io/"

[project.optional-dependencies]
testing = ["pytest", "syrupy>=5", "pytest-cov", "coverage[toml]", "myst-parser"]
docs = ["furo"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["B0", "C4", "I", "ICN", "ISC", "N", "RUF", "SIM", "UP"]
extend-ignore = ["ISC001", "RUF009"]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.mypy]
strict = true
show_error_codes = true

[tool.coverage.run]
omit = ["*/_private.py"]
